-- BORRAR TABLAS

-- SELECCIONAR BASE DE DATOS
USE libreria;
SET NAMES utf8mb4;

-- VER VARIABLE GLOBAL
SHOW VARIABLES LIKE "SQL_SAFE_UPDATES";
-- DESHABILITAR ACTUALIZACION SEGURA
SET SQL_SAFE_UPDATES = 0;

-- TABLE DELETE
DELETE FROM libreria_libro;
-- SELECCIONAR TABLA
SELECT * FROM libreria_libro;

-- HABILITAR ACTUALIZACION SEGURA
SET SQL_SAFE_UPDATES = 1;
-- VER VARIABLE GLOBAL
SHOW VARIABLES LIKE "SQL_SAFE_UPDATES";